#!/bin/bash
#SBATCH --job-name=DRC_GIT
#SBATCH -N 1
#SBATCH -n 64
#SBATCH --output matlab.out
#SBATCH --error matlab.err
#SBATCH -p heydenlab-64core

module purge

module load matlab/R2020a

cat << jide

 $(date)

 ${SLURM_JOB_NAME}

 ${SLURM_JOB_ID}

 $(hostname)

 ${SLURM_JOB_NODELIST}

jide

matlab -batch "C2_Pt_111_rework" >& log
