#!/bin/bash
#SBATCH --job-name=RC_01_02
#SBATCH -N 1
#SBATCH -n 128
#SBATCH --output matlab.out
#SBATCH --error matlab.err
#SBATCH -p wholenode
#SBATCH -t 6:00:00

module purge

module load matlab/R2023a

cat << jide

 $(date)

 ${SLURM_JOB_NAME}

 ${SLURM_JOB_ID}

 $(hostname)

 ${SLURM_JOB_NODELIST}

jide

#run the application:
matlab -nodisplay -singleCompThread -r C2_Pt_111_main_script
